### ISSUE TITLE
增加TV自适应文字高度可好

### ISSUE THREAD

**Issue by XHJiang** [lifution/FSTextView#1]
最好能有放在cell里面的案例

**Comment by lifution** [comment]
能具体说一下你的需求吗 ?

**Comment by XHJiang** [comment]
就是说,这个textView会根据我输入的内容,自动增大自身高度,有个最大值这种,类似QQ输入框,我有实现过,但是如果把这个tv放到tableView上面让cell也跟着变高,这种Demo,能不能提供一下

**Comment by lifution** [comment]
明白你的意思了, 这样吧, 这周末我抽空实现一下.
