### ISSUE TITLE
长按后弹出的UIMenuController,点击删除会闪退，因为没有实现delete方法

### ISSUE THREAD

**Issue by luckyzd** [lifution/FSTextView#10]
长按后弹出的UIMenuController,点击删除会闪退，因为没有实现delete方法

**Comment by lifution** [comment]
`UITextView` 的 `UIMenuController` 貌似没有 `delete` 的选项吧 ?

**Comment by luckyzd** [comment]
有，这是测试给我提的BUG

**Comment by luckyzd** [comment]
有，这是测试给我提的bug
在- (BOOL)canPerformAction:(SEL)action withSender:(id)sender 里面加了判断
if(action ==@selector(delete:))
    {
        return NO;
    }
这样就把删除隐藏了

**Comment by lifution** [comment]
判断弹出 `UIMenuController` 的选项, 我是这样判断的, 如果 `[super canPerformAction:action withSender:sender]` 返回的是 `YES` 我才根据 `FSTextView` 的属性 `canPerformAction` 来判断是否需要弹出 `UIMenuController` 选项. 如果基类 `UITextView` 都无法实现的 `action` 是会返回 `NO` 的. 可能你用的是以前的 `FSTextView` 版本, 如果你是使用 `Cocoapods` 引入 `FSTextView` 的话, 那应该是上一个版本的遗留问题, 最新的版本我还没有更新到 `Cocoapods` 上, 因为我最新正在修改 `FSTextView`, 准备下个版本再更新到 `Cocoapods` 上, 你看看你项目里的 `FSTextView` 的下面这个函数是否和这里的一致.
```ObjC
- (BOOL)canPerformAction:(SEL)action withSender:(id)sender
{
    BOOL result = [super canPerformAction:action withSender:sender];
    if (result) {
        result = _canPerformAction;
    }
    
    return result;
}
```

**Comment by luckyzd** [comment]
写法是和这里一致的，但是很奇怪，我能看到删除，但是点击删除就闪退
-[FSTextView delete:]: unrecognized selector sent to instance

**Comment by lifution** [comment]
我更新了一下代码, 同时也把最新版本更新到 `Cocoapods` 了, 你更新最新的版本试试, 感谢你的反馈. 🙂
