### ISSUE TITLE
menu删除崩溃，找不到方法

### ISSUE THREAD

**Issue by JoleneLiu** [lifution/FSTextView#12]
![image](https://user-images.githu
<img width="320" alt="42070233-973e-462c-80b2-e613849abdb1" src="https://user-images.githubusercontent.com/18735195/34929460-f69f9ca4-f9fe-11e7-8c4a-bd246f9c9565.png">
busercontent.com/18735195/34929437-d270422a-f9fe-11e7-9a9e-43b24662644b.png)

**Comment by lifution** [comment]
请更新最新版使用, 1.8版本已修复该问题.
