### ISSUE TITLE
maxLength设置了限制，但是直接复制文字进去后已经超过限制了还是能继续输入，继续复制

### ISSUE THREAD

**Issue by chenhde** [lifution/FSTextView#14]

**Comment by lifution** [comment]
这个控件目前在重构，预计明天能更新，新版已修复该问题。谢谢你的反馈。

**Comment by xubillde** [comment]
更新了吗？

**Comment by lifution** [comment]
@LDXu 这个控件太久没维护了，建议你改用 [QMUIKit](https://github.com/Tencent/QMUI_iOS)，这个框架里有一个封装得很不错的 UITextView (名为 QMUITextView)。
