### ISSUE TITLE
我们项目在release模式下,textview无法使用

### ISSUE THREAD

**Issue by hament** [lifution/FSTextView#15]
我们项目在release模式下,textview无法使用,无法触发弹出键盘, 但是debug模式可以

**Comment by lifution** [comment]
这个控件我很久没维护了，建议您改用 [QMUIKit](https://github.com/Tencent/QMUI_iOS)，这个组件里有一个非常优秀的 UITextView 控件封装，给您带来了不便，还望见谅。

**Comment by hament** [comment]
> 这个控件我很久没维护了，建议您改用 [QMUIKit](https://github.com/Tencent/QMUI_iOS)，这个组件里有一个非常优秀的 UITextView 控件封装，给您带来了不便，还望见谅。

好的,谢谢回复,我试试
