### ISSUE TITLE
看了下源码，写得很好

### ISSUE THREAD

**Issue by songxing10000** [lifution/FSTextView#2]
不知道有中文联想、英文，表情，之类的处理吗

**Comment by lifution** [comment]
最近比较忙, 过一段时间会加入相关的正则, 比如只能输入数字, 不允许输入Emoji表情, 只能输入英文等等平时开发常遇见的需求.

**Comment by songxing10000** [comment]
膜拜

Sent from Mail Master
在2016年10月20日 18:30，Steven 写道:

最近比较忙, 过一段时间会加入相关的正则, 比如只能输入数字, 不允许输入Emoji表情, 只能输入英文等等平时开发常遇见的需求.
