### ISSUE TITLE
项目里经常textview placehoder处理，字数限制，UITextField字数限制

### ISSUE THREAD

**Issue by songxing10000** [lifution/FSTextView#3]
期待field的作品，项目里试用FSTextView，有问题第一时间提交issue

**Comment by songxing10000** [comment]
storyboard中生成textview没效果，不解

**Comment by lifution** [comment]
你设置了Class为FSTextView了吗 ?

**Comment by songxing10000** [comment]
@lifution 设置了，在你demo上直接从xib sb中生成也不行，我给textview设置了背景色，填 fstextview背景色都没了

**Comment by lifution** [comment]
@songxing10000 已经修复了, 刚更新, 你重新下载替换一下就行.

**Comment by lifution** [comment]
@songxing10000 现在可以使用CocoaPods的方式引入FSTextView了, 你可以看看项目下的说明.😁

**Comment by songxing10000** [comment]
@lifution 期待textField

**Comment by songxing10000** [comment]
很完美，右下角那个输入剩余提示，有时还是有需要的，可以考虑加入此功能，默认不显示，有需求时设置成YES，即可显示
![simulator screen shot 2016 10 25 9 44 18](https://cloud.githubusercontent.com/assets/10040131/19672025/cf49997a-9aa5-11e6-8cf2-741afbf7c4b6.png)

**Comment by lifution** [comment]
@songxing10000 谢谢你的建议, 到时候会加入这个提示.

**Comment by kuangtao22** [comment]
请问下载swift中怎么纯代码使用
let textView = FSTextView(frame: CGRect(x: 0, y: self.navIV.bottom, width: screen_width, height: 200))
self.view.addSubview(textView)
这样返回的是空
正确怎么使用？？

**Comment by lifution** [comment]
@kuangtao22 你确定是nil而不是在UI上没看到吗 ? 你设置个背景色看看, 因为默认的背景色是白色的, 你这样初始化后没有做任何的设置, 所以看到的效果就是一片空白.
