### ISSUE TITLE
有一个很严重的bug.

### ISSUE THREAD

**Issue by MrQQQQQQQQQQ** [lifution/FSTextView#4]
- (void)textDidChange:(NSNotification *)notification，这个方法里 并没有判断 发生改变的textView 是否 是自身，当 同时存在 多个 实例的时候，其中一个内容发生改变，其他 的textView 也会 跟着走这个方法，从而跟着改变。

**Comment by lifution** [comment]
@MrQQQQQQQQQQ 我测试了一下, 并没有影响到其它的, 每次只会回调当前键盘对应的`FSTextView`的`textDidChange:`方法, 我在这个方法里做了一个打印`NSLog(@"currentTextView: %p", notification.object);`, 然后来回切换两个`FSTextView`来编辑, 打印的都是正在编辑的`FSTextView`的指针. 你说的这种情况能提供个Demo我详细了解一下吗 ? 谢谢.

**Comment by MrQQQQQQQQQQ** [comment]
我的使用 场景是 tableview,多个cell ,每个cell 中 一个 textview,这个时候 就会有问题，其实想想也知道，这个使用 的是 通知，每个实例都 注册了 通知，其中一个 触发， 所有 注册了的实例 肯定都会 收到通知的

**Comment by lifution** [comment]
@MrQQQQQQQQQQ 已经修复了, 换了一种注册通知的方式, 你下载最新的下来替换进去看看还有没有你原来那个问题. 感谢你的 `issue`.

**Comment by lifution** [comment]
@MrQQQQQQQQQQ 如果没问题的话, 我就关闭这个会话了.
