### ISSUE TITLE
输入到限制字数后输入空格键会出现限制失效

### ISSUE THREAD

**Issue by Captain-Tsubasa** [lifution/FSTextView#5]
比如我限制输入的是20个字符，输入20个字符之后我第一次输入空格键，会超出限制输入不会回退，相当于我输入到了21长度的位置，这个时候我再输入空格的话会回退到20字符的地方，我继续从20字符的位置输入空格之后就完全失效了。这个期间手动回退到20字符以内限制就会重新生效

**Comment by lifution** [comment]
已修复, 谢谢你的 `issue`. 🙂

**Comment by Captain-Tsubasa** [comment]
哪里哪里，源码写得很不错，用起来很方便，谢谢分享
