### ISSUE TITLE
占位字符居中？

### ISSUE THREAD

**Issue by olderMonster** [lifution/FSTextView#7]
![simulator screen shot 2017 6 24 7 20 06](https://user-images.githubusercontent.com/9191869/27508168-2f077d0c-5912-11e7-9c86-95efd03c6431.png)

代码：
- (void)viewDidLoad {
    [super viewDidLoad];
    
    self.navigationItem.title = @"发布";
    self.view.backgroundColor = [UIColor whiteColor];
    
    [self.view addSubview:self.contentTextView];
    
}

- (FSTextView *)contentTextView{
    if (_contentTextView == nil) {
        _contentTextView = [FSTextView textView];
        _contentTextView.placeholder = @"沿路的风景...";
        
        _contentTextView.layer.masksToBounds = YES;
        _contentTextView.layer.cornerRadius = 3;
        _contentTextView.layer.borderColor = RGB(235, 235, 238).CGColor;
        _contentTextView.layer.borderWidth = 1.0f;
    }
    return _contentTextView;
}

- (void)viewWillLayoutSubviews{
    [super viewWillLayoutSubviews];
    
    self.contentTextView.frame = CGRectMake(20, 84, self.view.bounds.size.width - 40, 150);
    
}

**Comment by lifution** [comment]
@olderMonster  你好, 你能提供一下demo吗 ? 因为我copy这段代码测试了没有这种情况, 可能是其它因素的问题, 如果你能提供一个能重现这个问题的demo就最好. 谢谢.

**Comment by olderMonster** [comment]
写了个demo，还是垂直居中。但是我第一次用的时候的确是正常的，只是后来才出现那种情况~~
这个demo怎么给你哩

**Comment by lifution** [comment]
@olderMonster 发到我QQ邮箱吧.

**Comment by lifution** [comment]
@olderMonster 找到原因了, 因为 `UITextView` 是继承于 `UIScrollView` 的, 因此被第一个 add 到控制器的视图上时会自动偏离顶部的 `UINavigationBar` (如果存在) 和 `UIStatusBar` 的高度 `64/20 Point` 的, 如果有页面是需要把 `FSTextView` 第一个添加到视图上的话, 在 `viewDidLoad` 方法里面加上一句 `self.automaticallyAdjustsScrollViewInsets = NO;` 就行了.

**Comment by olderMonster** [comment]
恩，的确是这个问题~~现在正常了，，谢谢啦
